---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age1mygsamn6hdll69y758mfwcrz7wuptgkqjpqjl50z52qy89m8q5vsuj8fw7"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1mygsamn6hdll69y758mfwcrz7wuptgkqjpqjl50z52qy89m8q5vsuj8fw7"
stores:
  yaml:
    indent: 2
